# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_arrays <- function(n_samples, lookback, n_features) {
    .Call('_aion_get_arrays', PACKAGE = 'aion', n_samples, lookback, n_features)
}

