# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_arrays <- function(data, ts_starts, lookback, horizon, past_var, fut_var) {
    .Call(`_aion_get_arrays`, data, ts_starts, lookback, horizon, past_var, fut_var)
}

